### ISSUE TITLE
variation generation not working correctly

### ISSUE THREAD

**Issue by slimani-dev** [Kamona-WD/tailwindcss-directions#1]
i did follow the instruction to add the variations but i got this result instezad

```css
[dir="rtl"] .rtl\:mr-2,[dir="ltr"] .ltr\:mr-2 {
  margin-right: 0.5rem;
}
```
